server:
  port: 8081
spring:
  application:
    name: spb-client-service
eureka:
  client:
    service-url:
      defaultZone:
        http://localhost:8761/eureka/
grpc:
  client:
    spb-server-service:
      negotiationType: plaintext
