server:
  port: 8761
eureka:
  server:
    enable-self-preservation: false
  instance:
    appname: eureka-server
    hostname: localhost
  client:
    service-url:
      defaultZone:
        http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: false